package View;

import Controller.PharmacyController;
import Model.PharmacyItem;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.List; // Import List from java.util package

public class LowStockNotificationView extends javax.swing.JFrame {
    private PharmacyController controller = new PharmacyController();

    /**
     * Creates new form LowStockNotificationView
     */
    public LowStockNotificationView() {
        initComponents();
        controller = new PharmacyController();  // Initialize controller here

        // Load low stock data into the table
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        HeaderTxt = new javax.swing.JLabel();
        TableScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        Buttons = new javax.swing.JPanel();
        CloseBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Low Stock Notification");

        Header.setBackground(new java.awt.Color(204, 204, 204));

        HeaderTxt.setBackground(new java.awt.Color(0, 0, 0));
        HeaderTxt.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        HeaderTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeaderTxt.setText("Low Stock Items");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
                HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HeaderLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(HeaderTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
                HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HeaderLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(HeaderTxt)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Table.setBackground(new java.awt.Color(204, 255, 255));
        Table.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        Table.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "ID", "Name", "Quantity", "Price (LKR)", "Exp Date"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableScrollPane1.setViewportView(Table);

        Buttons.setBackground(new java.awt.Color(204, 204, 204));

        CloseBtn.setBackground(new java.awt.Color(204, 204, 255));
        CloseBtn.setText("Close");
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonsLayout = new javax.swing.GroupLayout(Buttons);
        Buttons.setLayout(ButtonsLayout);
        ButtonsLayout.setHorizontalGroup(
                ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ButtonsLayout.createSequentialGroup()
                                .addGap(300, 300, 300)
                                .addComponent(CloseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(300, Short.MAX_VALUE))
        );
        ButtonsLayout.setVerticalGroup(
                ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonsLayout.createSequentialGroup()
                                .addContainerGap(20, Short.MAX_VALUE)
                                .addComponent(CloseBtn)
                                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TableScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Buttons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TableScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        // Close the current window
        this.dispose();
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void updateTable() {
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        model.setRowCount(0); // Clear existing rows

        // Fetch low stock items from the database
        List<PharmacyItem> lowStockItems = controller.getLowStockItems();

        // Add low stock items to the table
        for (PharmacyItem item : lowStockItems) {
            model.addRow(new Object[]{
                    item.getId(),
                    item.getName(),
                    item.getQuantity(),
                    item.getPrice(),
                    item.getExpDate()
            });
        }

        // Show a warning popup if low stock items are found
        if (model.getRowCount() > 0) {
            JOptionPane.showMessageDialog(
                    this, // Parent component (the current window)
                    "⚠ WARNING: Some medicines are in low stock!", // Message
                    "Low Stock Alert", // Title
                    JOptionPane.WARNING_MESSAGE // Message type (warning icon)
            );
        } else {
            // Show a success message if no low stock items are found
            JOptionPane.showMessageDialog(
                    this,
                    "✅ All stock levels are sufficient.",
                    "Low Stock Notification",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LowStockNotificationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LowStockNotificationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LowStockNotificationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LowStockNotificationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LowStockNotificationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Buttons;
    private javax.swing.JButton CloseBtn;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel HeaderTxt;
    private javax.swing.JTable Table;
    private javax.swing.JScrollPane TableScrollPane1;
    // End of variables declaration//GEN-END:variables
}
