package Home;

import View.MainUI;
import View.PharmacyView;
import View.Doctorview;
import View.MainUI;

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form PharmacyManagementUI
     */
    public Home() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FooterTxt = new javax.swing.JPanel();
        DoctorBtn = new javax.swing.JButton();
        PatientBtn = new javax.swing.JButton();
        PharmacyBtn = new javax.swing.JButton();
        AppoinmentBtn = new javax.swing.JButton();
        ReportsBtn = new javax.swing.JButton();
        NotiPatientBtn = new javax.swing.JButton();
        NotiPharmacistsBtn = new javax.swing.JButton();
        Header = new javax.swing.JPanel();
        HeaderTxt = new javax.swing.JLabel();
        Footer = new javax.swing.JPanel();
        RightTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DoctorBtn.setBackground(new java.awt.Color(0, 103, 206));
        DoctorBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DoctorBtn.setForeground(new java.awt.Color(255, 255, 255));
        DoctorBtn.setText("Manage Doctor Shedules");
        DoctorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorBtnActionPerformed(evt);
         }
});

        PatientBtn.setBackground(new java.awt.Color(0, 103, 206));
        PatientBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PatientBtn.setForeground(new java.awt.Color(255, 255, 255));
        PatientBtn.setText("Manage Patient Records");
        PatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientBtnActionPerformed(evt);
            }
        });

        PharmacyBtn.setBackground(new java.awt.Color(0, 103, 206));
        PharmacyBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PharmacyBtn.setForeground(new java.awt.Color(255, 255, 255));
        PharmacyBtn.setText("Manage Pharmacy Inventory");
        PharmacyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PharmacyBtnActionPerformed(evt);
            }
        });

        AppoinmentBtn.setBackground(new java.awt.Color(0, 103, 206));
        AppoinmentBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AppoinmentBtn.setForeground(new java.awt.Color(255, 255, 255));
        AppoinmentBtn.setText("Book Appoinments");

        ReportsBtn.setBackground(new java.awt.Color(0, 103, 206));
        ReportsBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ReportsBtn.setForeground(new java.awt.Color(255, 255, 255));
        ReportsBtn.setText("Monthly Reports");
        ReportsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportsBtnActionPerformed(evt);
            }
        });

        NotiPatientBtn.setBackground(new java.awt.Color(0, 103, 206));
        NotiPatientBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NotiPatientBtn.setForeground(new java.awt.Color(255, 255, 255));
        NotiPatientBtn.setText("Notify Patients");

        NotiPharmacistsBtn.setBackground(new java.awt.Color(0, 103, 206));
        NotiPharmacistsBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NotiPharmacistsBtn.setForeground(new java.awt.Color(255, 255, 255));
        NotiPharmacistsBtn.setText("Notify Pharmacists");

        javax.swing.GroupLayout FooterTxtLayout = new javax.swing.GroupLayout(FooterTxt);
        FooterTxt.setLayout(FooterTxtLayout);
        FooterTxtLayout.setHorizontalGroup(
            FooterTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterTxtLayout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addGroup(FooterTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NotiPharmacistsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FooterTxtLayout.createSequentialGroup()
                        .addGroup(FooterTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ReportsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PharmacyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatientBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(FooterTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DoctorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AppoinmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NotiPatientBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(162, 162, 162))
        );
        FooterTxtLayout.setVerticalGroup(
            FooterTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterTxtLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(FooterTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FooterTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PharmacyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AppoinmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FooterTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReportsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NotiPatientBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(NotiPharmacistsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        Header.setBackground(new java.awt.Color(0, 103, 206));

        HeaderTxt.setBackground(new java.awt.Color(255, 255, 255));
        HeaderTxt.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        HeaderTxt.setForeground(new java.awt.Color(255, 255, 255));
        HeaderTxt.setText("MediCarePlus Management System");
        HeaderTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(HeaderTxt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HeaderTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Footer.setBackground(new java.awt.Color(204, 204, 204));

        RightTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RightTxt.setText("© 2024 Medicareplus. All Right Reserved.");

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RightTxt)
                .addGap(294, 294, 294))
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(RightTxt)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FooterTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FooterTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PharmacyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PharmacyBtnActionPerformed
        // Create an instance of PharmacyView
    PharmacyView pharmacyView = new PharmacyView();
    
    // Set PharmacyView visible
    pharmacyView.setVisible(true);
    
    // Optionally close the current window (Home)
    this.setVisible(false); // This hides the current window
    // Or you can dispose it to free up resources
    // this.dispose();
    }//GEN-LAST:event_PharmacyBtnActionPerformed

    private void DoctorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorBtnActionPerformed
        // Create an instance of DoctorView
        Doctorview doctorView = new Doctorview();

        // Set DoctorView visible
        doctorView.setVisible(true);

        // Optionally close the current window (Home)
        this.setVisible(false); // This hides the current window
        // Or you can dispose of it to free up resources
        // this.dispose();
    }//GEN-LAST:event_DoctorBtnActionPerformed

    private void ReportsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorBtnActionPerformed
        // Create an instance of DoctorView
        MainUI mainui = new MainUI();

        // Set DoctorView visible
        mainui.setVisible(true);

        // Optionally close the current window (Home)
        this.setVisible(false); // This hides the current window
        // Or you can dispose of it to free up resources
        // this.dispose();//Hi
    }//GEN-LAST:event_DoctorBtnActionPerformed


    private void PatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AppoinmentBtn;
    private javax.swing.JButton DoctorBtn;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel FooterTxt;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel HeaderTxt;
    private javax.swing.JButton NotiPatientBtn;
    private javax.swing.JButton NotiPharmacistsBtn;
    private javax.swing.JButton PatientBtn;
    private javax.swing.JButton PharmacyBtn;
    private javax.swing.JButton ReportsBtn;
    private javax.swing.JLabel RightTxt;

}
